### ISSUE TITLE
NANRremove can be replaced with  k[is.finite(k)&is.finite(r)]?

### ISSUE THREAD

**Issue by kmclaren-trinity** [Trinity-Automata-Research/dsmodels#101]
much simpler, r style way of doing it.

is.finite(k) is a vector of booleans so k[is.finite(k)] is the finite elements of k

**Comment by kmclaren-trinity** [comment]
This also means boolpos is unneccesary

**Comment by sfogarty** [comment]
Fixed with #223 in #225
