### ISSUE TITLE
GuessPeriodicAttractors

### ISSUE THREAD

**Issue by sfogarty** [Trinity-Automata-Research/dsmodels#51]
Function similary to guessAttractors, but after iters steps, unstable points should be pruned for duplicates and then iterated to find their period.

**Comment by kmclaren-trinity** [comment]
the find.period method in convergenceTesting is pretty much this. should be added to dsmodels

will also need the finite.points, has.diverged and sqdist functions

**Comment by kmclaren-trinity** [comment]
duplicate of #111
