### ISSUE TITLE
Allow expressions in dscurve

### ISSUE THREAD

**Issue by sfogarty** [Trinity-Automata-Research/dsmodels#7]
<a href="https://github.com/sfogarty"><img src="https://avatars.githubusercontent.com/u/4805512?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sfogarty](https://github.com/sfogarty)**
_Thursday Jun 30, 2016 at 19:19 GMT_
_Originally opened as https://github.com/Trinity-Automata-Research/dynamical-systems-dsl/issues/22_

---

i.e. dscurve(t, (1-t), col="red", image="green")
Parse the input and find all undefined variables?
Automatically create function(param1, param2, param3) {fun}
See how this is done in ggplot or others. Probably easier way to do this. We saw someone be able to do this when we were looking at ways of plotting out curves.

**Comment by sfogarty** [comment]
Also in dsmodel.

**Comment by sfogarty** [comment]
dsmodel is either taking expressions or a single function. To determine which:

* If a single parameter is provided, it must be a function.
* If two parameters are provided, check if the first has any free variables.
  * If it does not, check if it is a function.
    * If so, must be a function.
    * If it is NOT a function, then must be expressions.
  * If it does, check if they are x, y, X, Y, X0, Y0, in sane combinations (including subset like {x})
    * If the free variables are sane , then must be expressions.
    * If the free variables are not sane, then throw an error.

free.vars <- function(x) {
  setdiff(all.vars(substitute(x)),ls(parent.frame()))
}

**Comment by sfogarty** [comment]
If we get a function, then check if the second parameter is set, but the title was not. If so, the second parameter should be the title.

Also, should check that it is a function of two arguments, that returns a list (somehow??)

**Comment by sfogarty** [comment]
If we get expressions, check that the second parameter has sane free variables.

**Comment by sfogarty** [comment]
dscurve ALREADY has dispatch. So if you have a single paremter, you're a graph curve. Check 
```
free.vars <- function(x) {
  setdiff(all.vars(substitute(x)),ls(parent.frame()))
}
```

- [ ] If the free variables are empty, then check that it is a function with a single argument, and if so you're great.  Dispatch.
- [ ] If the free variables are x or X, then use makeXFunction below. We might be able to generalize this to ANY single free variable. Then dispatch exactly the same as above.

```
makeXFun <- function(xpr) {
  xexp <- substitute(xpr)
  enc <- parent.frame()
  function(xinp) {
      eval(xexp,list(x=xinp),enc)
    )
}
```

If you play around with pryr, you might get the below to work:
```
makeYFun <- function(bdy)
  make_function(alist(y=), substitute(bdy), parent.frame())
```

**Comment by sfogarty** [comment]
If you have two parameters, you're a parameteric curve. Check the free variables of both parameters, and go through the same process above, but for t and T instead of x and X.

**Comment by cstein1** [comment]
`function(x) {input1}` was malfunctioning. I fixed it in the pull request on branch #65

**Comment by cstein1** [comment]
I'm having an issue where 
```
free.vars(function(x) x+1)
```
is returning `"x"`. I'm going to do more research, but did you figure out if there is a way to know whether the input is a function or not?

**Comment by sfogarty** [comment]
free.vars doesn't work! It does not consider variables defined IN the expression.

Instead, we can check if it's a function using 
```
is.function.safe <- function(expr) {
  tryCatch({is.function(expr)},
           error=function(e) { FALSE } )
}
```

If it is a function, then we can check the parameters and make sure there is a single  element of formals(f).

If it is not a function, then we can make it a function, but we need to know what variable to bind.  For now, use free.vars and we just won't allow variable definitions inside of the expressions.

**Comment by sfogarty** [comment]
For now, just hard-code, if is.function.safe fails, make them functions of t (parametric), or x (graph)

**Comment by sfogarty** [comment]
eventually, we'll want to do something like findGlobals to make sure our created functions are closed. For now, on the users head be it.

**Comment by sfogarty** [comment]
For now,you could even simply use   
`make_function(alist(x=), substitute(prm), parent.frame())`
and 
`make_function(alist(t=), substitute(prm), parent.frame())`
