### ISSUE TITLE
Support parameterized curves with a list in dscurve

### ISSUE THREAD

**Issue by sfogarty** [Trinity-Automata-Research/dsmodels#8]
<a href="https://github.com/sfogarty"><img src="https://avatars.githubusercontent.com/u/4805512?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sfogarty](https://github.com/sfogarty)**
_Thursday Jun 30, 2016 at 19:20 GMT_
_Originally opened as https://github.com/Trinity-Automata-Research/dynamical-systems-dsl/issues/23_

---

I really want to be able to say
dscurve(function t { list(x-1, y-1) }, col="red"), but how can we tell this isn't a non-parameterized curve?

**Comment by cstein1** [comment]
When you are checking that the single input is a function, if it has one parameter, then it is what you expect. If it has two parameters, then life gets more complicated, see if you have to refactor what you would dispatch that to.
