### ISSUE TITLE
display=FALSE doesn't calculate things, because render is mixed up with onBind. Solution: create onBind.

### ISSUE THREAD

**Issue by sfogarty** [Trinity-Automata-Research/dsmodels#82]

**Comment by sfogarty** [comment]
if I want to make a function that does nothing, is "  onBind = function(self, model) {0}" the right way?

**Comment by cstein1** [comment]
I'm not quite sure.
It seems as if returning a value without changing anything can be correct.
You can also utilize the `return` function and have something like

```
onBind = function(self, model) {return()}
```

and a `NULL` value will be returned. It seems like a 100% preferential, as
this is not a normal action in R.
