### ISSUE TITLE
Make pretty dynamical system pictures in  raw r.

### ISSUE THREAD

**Issue by sfogarty** [Trinity-Automata-Research/dsmodels#84]
After #83 , make a way to test the stability of a dynamical system with that point's parameters and color a pretty picture accordingly (in raw R)

**Comment by sfogarty** [comment]
First step: find a dynamical system that is sometimes stable, and sometimes not. Come up with a function to test it.

**Comment by sfogarty** [comment]
Will also probably require #82 to be implemented first.

**Comment by kmclaren-trinity** [comment]
improving existing sims
- [x] checking for nan's
- [x] use crop?--- no, the length of points put in must be the same as the length of points returned by apply so distances can be calculated.
- [x] init iters
- [x] divergence handling

**Comment by kmclaren-trinity** [comment]
- [x] grid methods in dsrange- corners and centers, return a x0, y0, and grid
- [x] converge at all
- [x] converge to one attractor
- [x] converge to one attractor off the axis

new sims

- [ ] revisit epsilon/tolerance
- [x] other ways to check stabilty
- [x] sim is stable at a single point
- [ ] is repeller?

**Comment by kmclaren-trinity** [comment]
applyTillFixed calls apply which checks for and removes nan's, but then applyTillFixed finds the square of the distance moved, which can be nan.

**Comment by kmclaren-trinity** [comment]
running sim basins with iters=Inf apparently wasnt working. it was missing a parameter in applyTillFixed and epsilon was always set to 0 in find nearest point. I added the parameter and set epsilon to self$epsilon

**Comment by kmclaren-trinity** [comment]
three ways to run simbasisn-
iters=null - default, uses the method findFixedPoint in dspoint.R
iters=Inf - uses applyTillFixed
iters= some number- applies the function exactly iters times, then checks if fixed points have been reached.

there seems to be a lot of overlap between findFixedPoint and applyTillFixed

**Comment by kmclaren-trinity** [comment]
model$warnPeriodic does nothing right now
