### ISSUE TITLE
Decide on "2d bifurcation diagram" name and syntax

### ISSUE THREAD

**Issue by sfogarty** [Trinity-Automata-Research/dsmodels#85]
After #84, figure out what the proper dsmodels primitives/objects should be, and how the code should look.

**Comment by kmclaren-trinity** [comment]
we will need parameterized functions:

parammodel(fun, nameOfParams)
paramrange(2:4,2:4)  different from dsrange
bifmap(x,y,...)  makes a bifurcation diagram
